### ISSUE TITLE
Add an Architecture overview page for Boost

### ISSUE THREAD

**Issue by jacobheun** [filecoin-project/boost-docs#1]
## Area's to cover
* How does Boost interact with Lotus?
  * What data/processing is being handled by Lotus, and what is handled by Boost?
* How does Boost interact with the Network?
* How are deals processed?

**Comment by LexLuthr** [comment]
Points we would want to cover under architecture.

1. Network and security boundaries as most of the SPs would not like to expose thing to internet unless necessary. We have to draw a clear picture of data flow and ports.
2. Where does boost fit within lotus. How and when boost contacts the lotus node and lotus-miner.
3. Add deal step details in UI as "info" button.
4. A architecture diagram is possible for major components within the boost.  We can list out sub-components in the doc for those who are interested to read about them.
