### ISSUE TITLE
Add a features page to list out the various things Boost supports

### ISSUE THREAD

**Issue by jacobheun** [filecoin-project/boost-docs#12]
This may supplement or be taken care of by adding https://github.com/filecoin-project/boost-docs/issues/11, but ensuring potential and existing users can see what's all supported very quickly could be a big draw for folks. 

Some examples:
* Storage deal transfer via http
* Storage deal transfer via http over libp2p (basic libp2p transfer)
* Backwards compatibility with go-fil-markets
* A client for proposing deals that doesn't require a full node

General thought for page structure is a brief title and summary of key features. Ex:

## Make storage deals with HTTP data transfer
Boost supports multiple options for data transfer when making storage deals, including HTTP. Users can host their CAR file on an http server, such as S3, and provide that url when proposing the storage deal. Once accepted, Boost will automatically fetch the CAR file from the specified url. See the <client/api> docs for details on how to do this.

**Comment by dirkmc** [comment]
Added Features section on the [main docs page](https://boost.filecoin.io).
