### ISSUE TITLE
--max-staging-deals-bytes description | readme.md

### ISSUE THREAD

**Issue by dd45e640b42e6da7da96faee3996ef7c** [filecoin-project/boost-docs#8]
> --max-staging-deals-bytes is the size of the space where Boost stores downloaded files

this is not the size of the space where boost stores downloaded files but the max combined size of the downloaded files to store in that location

**Comment by dirkmc** [comment]
Changed to

`--max-staging-deals-bytes` is the maximum amount of storage to be used for downloaded files (once the limit is reached Boost will reject subsequent incoming deals)
