### ISSUE TITLE
https://github.com/filecoin-project/boost#web-ui vs. what the readme.md says

### ISSUE THREAD

**Issue by dd45e640b42e6da7da96faee3996ef7c** [filecoin-project/boost-docs#9]
according to the boost repo one needs to start the GUI by hand - the documentation readme claims it gets started with the `boost -vv run` command

**Comment by dirkmc** [comment]
The Boost README states how to install and build the GUI. These instructions are correct:
<img width="474" alt="Screen Shot 2022-03-22 at 5 40 57 PM" src="https://user-images.githubusercontent.com/169124/159530688-1952b732-f5a6-4529-97f3-8449613730f1.png">

**Comment by dd45e640b42e6da7da96faee3996ef7c** [comment]
right. now the boost-docs include that too
